=== ggthjew4/JavaProject/webservice-ticket/src/main/java/com/bluetechnology/webservice_ticket/test/BTHibetnateXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">
	<!-- definition of simple elements -->
	<xs:element name="bluetechnology-mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="type" use="required">
										<xs:annotation>
											<xs:documentation>
										    <![CDATA[ 欄位型別 ]]>
											</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="long" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="column" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="property"  maxOccurs="7" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="column" type="xs:string" use="required"/>
									<xs:attribute name="type" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="table" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ggthjew4/JavaProject/BT-Xml/src/main/resources/bt_hibernate.xml
<?xml version="1.0" encoding="UTF-8"?>
<bluetechnology-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BTHibetnateXMLSchema.xsd">
	<class name="com.bt.vo.BtUser" table="btuser">
		<id name="userSn" type="Integer" column="user_sn"/>
		<property name="userId" type="String" column="user_id"/>
		<property name="userName" type="String" column="user_name"/>
		<property name="userPwd" type="String" column="user_pwd"/>
		<property name="userAge" type="Integer" column="user_age"/>
		<property name="userVer" type="Integer" column="user_ver"/>
	</class>
</bluetechnology-mapping>
